### ISSUE TITLE
Error bundling

### ISSUE THREAD

**Issue by luandro** [staltz/react-native-ssb-client#1]
On newly created RN project I installed [react-native-scuttlebot](https://github.com/ssbc/react-native-scuttlebot), worked but got a few errors:
```
node-pre-gyp ERR! stack Error: Cannot find module 'internal/util/types'

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'pull-stream/throughs/map' from 'project/rnnodeapp/node_modules/flumelog-offset'
    at project/node_modules/noderify/bin.js:5537:31
```

Next I installed `react-native-ssb-client`, but just got the node-gyp error again.  I tried to run a simple app that uses sbot and client:
```
componentDidMount () {
    Scuttlebot.start();
    ssbClient(function (err, sbot) {
      sbot.whoami(function (err, info) {
        this.setState({
          me: info.id
        })
      })
    })
  }
```

But it doesn't bundle:

```
error: bundling failed: Error: Unable to resolve module `os` from `project/node_modules/os-homedir/index.js`: Module does not exist in the module map
```

**Comment by luandro** [comment]
Spent some more time debugging. 

Was able to get rid of the `node-gyp` errors by downgrading NodeJS to version 6.10.3.

Tried a couple of fresh installations to better understand what's throwing errors. `react-native-scuttlebot` works perfectly, but when I install `react-native-ssb-client` I start getting errors with `fs`. I than install `react-native-ssb-shims`, but still get errors with `fs`. Finally I install `react-native-fs`, which gets rid of all the errors, but it doesn't seem to bundle anything and I just end up with a blank screen and no logs.

I noticed that this package just a very thin wrapper for `ssb-client`. To actually get it to work do I need `react-native-ssb-shims` as well?

@staltz should this just work, or am I missing something important?

**Comment by staltz** [comment]
Yes you need ssb-shims package (short message because I'm on mobile and it's cold outside)

**Comment by luandro** [comment]
lol, no problems.

But even with ssb-shims I get errors that seem to be related to `react-native-fs`. I'll try starting fresh and post what I get.

**Comment by luandro** [comment]
Using node v6.10.3 (npm v3.10.10) running on MacOS Sierra. React-native 0.53.3. Installed:

`npm i -S react-native-scuttlebot react-native-ssb-client react-native-ssb-shims`

shims throws an error relating to packaging:

```
> patch-package

sh: patch-package: command not found
```

By `npm i -S patch-package` I can then install everything. Again scuttlebot throws error:

`Error: Cannot find module 'pull-stream/throughs/map' from project/rnnodeapp/node_modules/flumelog-offset'`

I also got this error when linking packages:

```
Scanning folders for symlinks in project/node_modules (20ms)
{ Error: Cannot find module 'project/node_modules/react-native-os/package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at getRNPMConfig (project/node_modules/react-native/local-cli/core/index.js:55:3)
    at Object.getDependencyConfig (project/node_modules/react-native/local-cli/core/index.js:117:18)
    at deps.reduce.err (project/node_modules/react-native/local-cli/link/getDependencyConfig.js:9:24)
    at Array.reduce (native)
    at getDependencyConfig (project/node_modules/react-native/local-cli/link/getDependencyConfig.js:6:15)
    at Object.link (project/node_modules/react-native/local-cli/link/link.js:133:24) code: 'MODULE_NOT_FOUND' }
```

By running `react-native run-android` I get:

```
project/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSPackage.java:20: error: method does not override or implement a method from a supertype
  @Override
  ^
Note: project/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-fs:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fs:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Seems to related to `react-native-fs`.

`tcp`, `fs`, `ramdom-bytes` and `node` all appear duplicated both in `android/app/buid.gradle`  and `android/settings.gradle`. I remove duplicates but it doesn't seem to have anything to do with it.

Finally I try `npm i -S react-native-fs`, which finally compiles but I get a red screen: `Native modules TcpSockets tried to override TcpSockets for module name TcpSockets...`. After that all I get is a blank screen. I haven't changed anything in the default `App.js` yet.

**Comment by staltz** [comment]
A couple of possible problems: npm 3. I think patch-package only works with npm 5 (e.g. v5.6.0).

the other issue is with react-native-os, I have been using a fork, @staltz/react-native-os try to compare with the mmmmm-mobile repo to see what's missing.

The goal is to have a plug-and-play react-native ssb library but in practice there are many hacks and things that can go wrong

**Comment by luandro** [comment]
Is that what you use `propagate-replacement-fields` for? By adding it and:
```json
 "react-native": {
    "os": "@staltz/react-native-os",
    "react-native-os": "@staltz/react-native-os",
    "rn-viewpager": "@staltz/rn-viewpager",
    "ssb-client": "react-native-ssb-client"
}
```
Would that be in the right direction? I could help getting closer to plug-and-play if I get it running.

**Comment by staltz** [comment]
Yes! `propagate-replacement-fields` will take that `"react-native":{"os":...` definition in the project's package.json and copy-paste it to all the package.jsons in dependencies. For `os` this is important. But this is all part of `react-native-ssb-shims` so it should already be plug-and-play, that's why I'm surprised

**Comment by luandro** [comment]
Shouldn't shims be a dependency for this module? Or at least be mentioned in the README?

Installed `react-native-ssb-shims` with node v8.9.3 and still get error that it's missing `patch-package`. 

Created an [issue](https://github.com/ssbc/react-native-ssb-shims/issues/3) at shims repo so we can start trying to fix that first.

**Comment by luandro** [comment]
Hey @staltz, I've been exploring mmmmm code a lot for the past weeks. I've been trying to reach you on Patchwork, but I just found out my stuff hasn't been replicated for the past 2 or 3 weeks (felt ignored). Anyways, now I understand that you've built this library in order to use `ssb-client` with `react-native-workers`, that's correct?

**Comment by staltz** [comment]
@luandro that's strange that you haven't been connected to other on Patchwork. You could try other Pubs. I followed you now, maybe that helps somewhat.

I built this library for different reason than what you said, and actually, surprisingly, this library should now be deprecated.

Originally, this library was doing two things: (1) providing shims for ssb libraries to work with react-native, (2) providing a manifest that would be used in the ssb config. These two things are now split out from this library. (1) is `react-native-ssb-shims` and (2) is now directly in the MMMMM app https://github.com/staltz/mmmmm-mobile/blob/c784e0d57327bc9a1a940f7a17f470402230601e/src/rnnodeapp/manifest.ts

**Comment by luandro** [comment]
That's kinda what I had figured. I've been doing exactly that for my experimentation, and just using normal `ssb-client`.

There's something wrong with my sbot, which I'm trying to get [some help](https://github.com/ssbc/scuttlebot/issues/476) with. Nothing I publish seems to get replicated.

Anyways, thanks a lot for MMMMM, it's opening up new doors for decentralized tech.
